package com.google.android.gms.internal.ads;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import java.util.Map;

/* JADX INFO: compiled from: com.google.android.gms:play-services-ads@@25.1.0 */
/* JADX INFO: loaded from: classes5.dex */
final class zzgde implements zzggl {
    private final zzgcu zzA;
    private final zzgda zzB;
    final zzimr zza;
    final zzimr zzb;
    final zzimr zzc;
    final zzimr zzd;
    final zzimr zze;
    final zzimr zzf;
    final zzimr zzg;
    final zzimr zzh;
    final zzimr zzi;
    final zzimr zzj;
    final zzimr zzk;
    final zzimr zzl;
    final zzimr zzm;
    final zzimr zzn;
    final zzimr zzo;
    final zzimr zzp;
    final zzimr zzq;
    final zzimr zzr;
    final zzimr zzs;
    final zzimr zzt;
    final zzimr zzu;
    final zzimr zzv;
    final zzimr zzw;
    final zzimr zzx;
    final zzimr zzy;
    final zzimr zzz;

    zzgde(zzgcu zzgcuVar, zzgda zzgdaVar, Context context, View view, Activity activity, String str, Map map, zzaxf zzaxfVar, zzgdl zzgdlVar) {
        this.zzA = zzgcuVar;
        this.zzB = zzgdaVar;
        zzimi zzimiVarZza = zzimj.zza(zzgdlVar);
        this.zza = zzimiVarZza;
        zzimi zzimiVarZzc = zzimj.zzc(str);
        this.zzb = zzimiVarZzc;
        zzimi zzimiVarZza2 = zzimj.zza(zzaxfVar);
        this.zzc = zzimiVarZza2;
        zzimr zzimrVar = zzgdaVar.zzb;
        zzimr zzimrVar2 = zzgcuVar.zza;
        zzimr zzimrVar3 = zzgcuVar.zzu;
        zzghw zzghwVarZza = zzghw.zza(zzimiVarZza2, zzimrVar, zzimrVar2, zzimrVar3);
        this.zzd = zzghwVarZza;
        zzghu zzghuVarZza = zzghu.zza(zzimiVarZza2, zzimrVar, zzimrVar3);
        this.zze = zzghuVarZza;
        zzimi zzimiVarZza3 = zzimj.zza(map);
        this.zzf = zzimiVarZza3;
        zzimr zzimrVar4 = zzgdaVar.zzb;
        zzimr zzimrVar5 = zzgcuVar.zzu;
        zzgic zzgicVarZza = zzgic.zza(zzimiVarZza2, zzimrVar4, zzimiVarZza3, zzimrVar5);
        this.zzg = zzgicVarZza;
        zzghy zzghyVarZza = zzghy.zza(zzimiVarZza2, zzimrVar4, zzgcuVar.zzj, zzimrVar5);
        this.zzh = zzghyVarZza;
        zzgim zzgimVarZza = zzgim.zza(zzimiVarZza2, zzimrVar4, zzimiVarZza, zzimiVarZza3, zzimrVar5);
        this.zzi = zzgimVarZza;
        zzgia zzgiaVarZza = zzgia.zza(zzimiVarZza2, zzimrVar4, zzimrVar5);
        this.zzj = zzgiaVarZza;
        zzimi zzimiVarZza4 = zzimj.zza(context);
        this.zzk = zzimiVarZza4;
        zzimr zzimrVar6 = zzgdaVar.zzb;
        zzimr zzimrVar7 = zzgcuVar.zzu;
        zzgii zzgiiVarZza = zzgii.zza(zzimiVarZza2, zzimrVar6, zzimiVarZza, zzimiVarZza4, zzimiVarZza3, zzimrVar7);
        this.zzl = zzgiiVarZza;
        zzimr zzimrVar8 = zzgcuVar.zza;
        zzimr zzimrVar9 = zzgcuVar.zzj;
        zzghs zzghsVarZza = zzghs.zza(zzimiVarZza2, zzimrVar6, zzimiVarZza3, zzimrVar8, zzimiVarZza, zzimrVar9, zzimrVar7);
        this.zzm = zzghsVarZza;
        zzgie zzgieVarZza = zzgie.zza(zzimiVarZza2, zzimrVar6, zzimrVar8, zzimrVar7);
        this.zzn = zzgieVarZza;
        zzgig zzgigVarZza = zzgig.zza(zzimiVarZza2, zzimrVar6, zzimiVarZza3, zzimrVar8, zzimrVar7);
        this.zzo = zzgigVarZza;
        zzghq zzghqVarZza = zzghq.zza(zzimiVarZza2, zzimiVarZza3, zzimrVar9, zzimrVar7);
        this.zzp = zzghqVarZza;
        zzimt zzimtVarZza = zzimu.zza(11, 0);
        zzimtVarZza.zza(zzghwVarZza);
        zzimtVarZza.zza(zzghuVarZza);
        zzimtVarZza.zza(zzgicVarZza);
        zzimtVarZza.zza(zzghyVarZza);
        zzimtVarZza.zza(zzgimVarZza);
        zzimtVarZza.zza(zzgiaVarZza);
        zzimtVarZza.zza(zzgiiVarZza);
        zzimtVarZza.zza(zzghsVarZza);
        zzimtVarZza.zza(zzgieVarZza);
        zzimtVarZza.zza(zzgigVarZza);
        zzimtVarZza.zza(zzghqVarZza);
        zzimu zzimuVarZzc = zzimtVarZza.zzc();
        this.zzq = zzimuVarZzc;
        zzimi zzimiVarZzc2 = zzimj.zzc(view);
        this.zzr = zzimiVarZzc2;
        zzimi zzimiVarZzc3 = zzimj.zzc(activity);
        this.zzs = zzimiVarZzc3;
        zzimr zzimrVar10 = zzgdaVar.zzb;
        zzimr zzimrVar11 = zzgcuVar.zzu;
        zzgho zzghoVarZza = zzgho.zza(zzimiVarZza2, zzimrVar10, zzimiVarZzc2, zzimiVarZzc3, zzimrVar11);
        this.zzt = zzghoVarZza;
        zzimr zzimrVarZza = zzimh.zza(zzggm.zza(zzimiVarZza4));
        this.zzu = zzimrVarZza;
        zzgiq zzgiqVarZza = zzgiq.zza(zzimiVarZza2, zzimrVar10, zzimrVarZza, zzimiVarZzc2, zzimrVar11);
        this.zzv = zzgiqVarZza;
        zzimt zzimtVarZza2 = zzimu.zza(11, 0);
        zzimtVarZza2.zza(zzghwVarZza);
        zzimtVarZza2.zza(zzghuVarZza);
        zzimtVarZza2.zza(zzghyVarZza);
        zzimtVarZza2.zza(zzghoVarZza);
        zzimtVarZza2.zza(zzgiqVarZza);
        zzimtVarZza2.zza(zzgimVarZza);
        zzimtVarZza2.zza(zzgiaVarZza);
        zzimtVarZza2.zza(zzgiiVarZza);
        zzimtVarZza2.zza(zzghsVarZza);
        zzimtVarZza2.zza(zzgieVarZza);
        zzimtVarZza2.zza(zzgigVarZza);
        zzimu zzimuVarZzc2 = zzimtVarZza2.zzc();
        this.zzw = zzimuVarZzc2;
        zzgio zzgioVarZza = zzgio.zza(zzimiVarZza2, zzgdaVar.zzb, zzimiVarZza3, zzimrVarZza, zzgcuVar.zzu);
        this.zzx = zzgioVarZza;
        zzimt zzimtVarZza3 = zzimu.zza(12, 0);
        zzimtVarZza3.zza(zzghwVarZza);
        zzimtVarZza3.zza(zzghuVarZza);
        zzimtVarZza3.zza(zzghyVarZza);
        zzimtVarZza3.zza(zzghoVarZza);
        zzimtVarZza3.zza(zzgiqVarZza);
        zzimtVarZza3.zza(zzgimVarZza);
        zzimtVarZza3.zza(zzgiaVarZza);
        zzimtVarZza3.zza(zzgiiVarZza);
        zzimtVarZza3.zza(zzghsVarZza);
        zzimtVarZza3.zza(zzgieVarZza);
        zzimtVarZza3.zza(zzgigVarZza);
        zzimtVarZza3.zza(zzgioVarZza);
        zzimu zzimuVarZzc3 = zzimtVarZza3.zzc();
        this.zzy = zzimuVarZzc3;
        this.zzz = zzimh.zza(zzggj.zza(zzgcuVar.zzx, zzgcuVar.zzG, zzgdaVar.zzb, zzimiVarZza, zzimiVarZzc, zzimiVarZza2, zzimuVarZzc, zzimuVarZzc2, zzimuVarZzc3, zzgcuVar.zzu));
    }

    @Override // com.google.android.gms.internal.ads.zzggl
    public final zzggi zza() {
        return (zzggi) this.zzz.zzb();
    }
}
