package com.fyber.inneractive.sdk.network;

import com.bytedance.sdk.openadsdk.TTAdConstant;
import com.digitalturbine.ignite.authenticator.events.EnumC4254d;
import com.ironsource.mediationsdk.logger.IronSourceError;
import java.util.HashMap;

/* JADX INFO: renamed from: com.fyber.inneractive.sdk.network.t */
/* JADX INFO: loaded from: classes4.dex */
public enum EnumC8415t {
    VAST_ERROR_DVC_FAILURE(46),
    FMP_SDK_INIT_FAILED(62),
    VAST_COMPANION_FAILED_LOADING(70),
    VAST_COMPANION_INCOMPATIBLE_MIMETYPE(75),
    FMP_COMPANION_FAILED_LOADING(78),
    ERROR_STORE_PROMO_FAILURE(96),
    VAST_ERROR_INVALID_RESPONSE(301),
    VAST_ERROR_TOO_MANY_WRAPPERS(302),
    VAST_ERROR_NO_MEDIA_FILES(303),
    VAST_ERROR_NO_COMPATIBLE_MEDIA_FILE(304),
    VAST_ERROR_PRE_BUFFER_TIMEOUT(306),
    VAST_ERROR_BUFFER_TIMEOUT(307),
    VAST_ERROR_FAILED_PLAYING_MEDIA_FILE(308),
    VAST_ERROR_FAILED_PLAYING_ALL_MEDIA_FILES(311),
    VAST_ERROR_UNSECURE_URL(312),
    MRAID_ERROR_UNSECURE_CONTENT(313),
    VPAID_ERROR_UNSECURE_CONTENT(314),
    MRAID_VIDEO_HAS_NOT_STARTED_PLAYING_IN_A_TIMELY_FASHION(390),
    VAST_UNKNOWN_PLAYER_ERROR(399),
    NATIVE_ERROR_INVALID_NATIVE_RESPONSE(401),
    NATIVE_ERROR_FAILED_TO_LOAD_AD(402),
    NATIVE_ERROR_MISMATCH_REQUIRED_ASSET_RESPONSE(404),
    NATIVE_ERROR_INVALID_REQUIRED_ASSET_DATA(405),
    NATIVE_ERROR_INVALID_OPTIONAL_ASSET_DATA(406),
    NATIVE_ERROR_INVALID_LINK_WEB_URL(407),
    NATIVE_ERROR_FAILED_LOAD_ASSET(410),
    NATIVE_ERROR_MISMATCH_OPTIONAL_ASSET_RESPONSE(411),
    NATIVE_ERROR_MISSING_PROTOCOL_REQUIRED_FIELD(412),
    NATIVE_ERROR_RECEIVED_VIDEO_BUT_NOT_SUPPORTED(TTAdConstant.VIDEO_INFO_CODE),
    NATIVE_ERROR_NO_VALID_URLS_FOR_CLICK(TTAdConstant.VIDEO_URL_CODE),
    NATIVE_ERROR_SOME_INVALID_URLS_FOR_PROCESSED_CLICK(TTAdConstant.VIDEO_COVER_URL_CODE),
    MRAID_AUTO_ACTION_DETECTED(501),
    FIRST_PARTY_EXTRA_DATA_ERROR(550),
    INTERNAL_CONFIG_MISMATCH(601),
    FATAL_ADM_PARSING_ERROR(603),
    FATAL_ADM_MARKUP_FETCHING_ERROR(604),
    TOKEN_EXCEEDS_LIMIT(605),
    IGNITE_FLOW_MODE_NOT_COMPATIBLE(606),
    IGNITE_FLOW_FAILED_TO_START(607),
    IGNITE_FLOW_FAILED_TO_INSTALL_APP(612),
    IGNITE_FLOW_FAILED_TO_LOAD_WEBPAGE(IronSourceError.ERROR_BN_RELOAD_SKIP_INVISIBLE),
    FATAL_CONFIGURATION_ERROR(701),
    FATAL_FEATURES_CONFIG_ERROR(704),
    IA_AD_LOAD_FAILED(801),
    IA_AD_EXPIRED(802),
    IA_AD_DESTROYED_WITHOUT_SHOW(803),
    IA_AD_FAILURE_DATA(850),
    CLICK_PARSING_FAILURE(991),
    MISSMATCH_SPOTID(992),
    FAILED_DNS(995),
    FETCH_TOKEN_DV_ERROR(1000),
    DV_ERROR_PHASE(1001),
    ODT_ENCRYPTION_EXCEPTION(EnumC4254d.ENCRYPTION_EXCEPTION.m20300a()),
    ODT_RAW_ONE_DT_ERROR(EnumC4254d.RAW_ONE_DT_ERROR.m20300a()),
    ODT_ONE_DT_PARSE_ERROR(EnumC4254d.ONE_DT_PARSE_ERROR.m20300a()),
    ODT_ONE_DT_AUTHENTICATION_ERROR(EnumC4254d.ONE_DT_AUTHENTICATION_ERROR.m20300a()),
    ODT_ONE_DT_BROADCAST_ERROR(EnumC4254d.ONE_DT_BROADCAST_ERROR.m20300a()),
    ODT_ONE_DT_REQUEST_ERROR(EnumC4254d.ONE_DT_REQUEST_ERROR.m20300a()),
    ODT_ONE_DT_GENERAL_ERROR(EnumC4254d.ONE_DT_GENERAL_ERROR.m20300a());

    private static final HashMap<Integer, EnumC8415t> sMap = new HashMap<>();
    int val;

    static {
        for (EnumC8415t enumC8415t : values()) {
            sMap.put(Integer.valueOf(enumC8415t.val), enumC8415t);
        }
    }

    EnumC8415t(int i) {
        this.val = i;
    }

    /* JADX INFO: renamed from: a */
    public static EnumC8415t m20785a(EnumC4254d enumC4254d) {
        return sMap.get(Integer.valueOf(enumC4254d.m20300a()));
    }
}
